# Generated by Django 3.2.4 on 2021-06-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_phonenumber_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact',
        ),
    ]
