# Generated by Django 3.2.4 on 2021-06-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_phonenumber_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
